// Copyright © 2026 The Things Network Foundation, The Things Industries B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Compiles the repository's schema.json into standalone Ajv validators that
// the submit/update wizards bundle, so the browser validates generated files
// against the exact same schema as `npm run validate` and CI.
//
// Runs automatically via the package.json `prebuild`/`prestart` hooks and
// writes src/js/lib/schema-validators.gen.js (gitignored).

const fs = require('fs')
const path = require('path')
const Ajv2020 = require('ajv/dist/2020')
const addFormats = require('ajv-formats')
const standaloneCode = require('ajv/dist/standalone').default

const schema = require('../../schema.json')
const payload = require('../../lib/payload.json')

const ajv = new Ajv2020({
  schemas: [payload, schema],
  code: { source: true },
  allErrors: true,
})
addFormats(ajv)

const schemaId = 'https://schema.thethings.network/devicerepository/1/schema'

const code = standaloneCode(ajv, {
  validateEndDevice: `${schemaId}#/$defs/endDevice`,
  validateEndDeviceProfile: `${schemaId}#/$defs/endDeviceProfile`,
  validateEndDevicePayloadCodec: `${schemaId}#/$defs/endDevicePayloadCodec`,
  validateVendorIndex: `${schemaId}#/$defs/vendorIndex`,
  validateVendorsIndex: `${schemaId}#/$defs/vendorsIndex`,
})

const out = path.join(__dirname, '..', 'src', 'js', 'lib', 'schema-validators.gen.js')
fs.writeFileSync(out, '// Generated by tools/compile-schema.js — do not edit.\n' + code)
console.log(`schema validators written to ${path.relative(process.cwd(), out)}`)
