baseURL = "https://www.thethingsnetwork.org/device-repository"
languageCode = "en-us"
title = "Device Repository for LoRaWAN"

[taxonomies]
  tag = "tags"

[params]
  author = "The Things Network"
  github = "https://github.com/TheThingsNetwork/lorawan-devices"
  facebook = "https://www.facebook.com/thethingsnetwork"
  og_image = "assets/ttn_profile_picture_white_bg.png"
  sitename = "The Things Network"
  twitter = "@thethingsntwrk"
