name: Triage New Issues
on:
  issues:
    types: [opened]

jobs:
  triage:
    name: Triage New Issues
    runs-on: ubuntu-latest
    steps:
      - name: Add "needs/triage" label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs/triage']
            })
