name: Release Device Repository

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release Device Repository
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '~1.15'
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '~14'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
        # extended: true
    - name: Download Go dependencies
      run: |
        cd website/
        make go.deps
    - name: Build content
      run: |
        cd website/
        make go.build
    - name: Build assets
      run: |
        cd website/
        yarn install
        yarn build
    - name: Build Hugo
      run: |
        cd website/
        hugo --minify
    - name: Deploy Device Repository to Github pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: website/public
