name: Validate
on: [push, pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: make deps
      - name: Validate
        run: make validate
      - name: Check Format
        run: npx prettier --check schema.json "vendor/**/*.yaml" "bin/**/*.js"
